name = "Aloha to Adventure"
author = "jjszaniszlo"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f9fb092a4e6838cccb81f4a356d6199bcf269fa6902cc9ae6796b0164897b2d1"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
