name = "Aloha to Adventure"
author = "jjszaniszlo"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5293297f4491da3e7b1aacecaebf02362e045af7bc6a39b386b677b7fb6bdfd9"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
