name = "Aloha to Adventure"
author = "jjszaniszlo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "81951c744c91b9a4281a7590cb40eddf8ebee8cfe67be57dc5a85449f984a766"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
