name = "Aloha to Adventure"
author = "jjszaniszlo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e843c793c0b5142bbfcbe1059c874251f876e01b85855517ec6675f946eee505"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
